version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build App
          command:
            dotnet build
      - run:
          name: Test
          command:
            dotnet test --logger "junit;LogFilePath=../test-results/results.xml"
      - store_test_results:
          path: test-results